name: Test demo
on: 
Â Â push:
Â Â Â Â branches: [ main ]
Â Â Â Â paths-ignore: [.github/**]
Â Â pull_request:
Â Â Â Â branches: [ main ]
Â Â schedule:
Â Â Â Â - cron: '12 8 * * 2'
Â Â workflow_dispatch:
jobs:
Â Â Build:
Â Â Â Â runs-on: ubuntu-latest
Â Â Â Â steps:
Â Â Â Â Â Â - run: 
          echo "ðŸŽ‰ The job was triggered by event: ${{ github.event_name }}"
          echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ."

Â Â Â Â Â Â - uses: actions/checkout@v3.3.0

Â Â Â Â Â Â - name: List files in the repository
Â Â Â Â Â Â Â Â run: |
Â Â Â Â Â Â Â Â Â Â echo "The repository ${{ github.repository }} contains the following files:"
Â Â Â Â Â Â Â Â Â Â tree
